routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {

    Route::get('/home', 'HomeController@index')->name('home');
    //projects related routes 
    Route::resource('projects','ProjectController')->only(['index', 'store']);;
    //tasks routes
    Route::resource('tasks','TaskController')->except(['create', 'show']);
    //task status update route
    Route::post('task_status','TaskController@TaskStatus')->name('task_status');
    //setup task order route
    Route::post('task_order','TaskController@TaskOrder')->name('task_order');
});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Auth;
class Project extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = ['project_name','created_by','updated_by','deleted_by'];

    public static function boot() {
        parent::boot();
  
        // create a event to happen on updating
        static::updating(function($table)  {
            $table->updated_by = auth()->user()->id;
        });
  
        // create a event to happen on deleting
        static::deleting(function($table)  {
            $table->deleted_by = auth()->user()->id;
        });
  
        // create a event to happen on saving
        static::creating(function($table)  {
            if (Auth::user()) {
                $table->created_by = auth()->user()->id;
            }
        });
      }

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;
use App\Http\Requests\ProjectRequest;


class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects=Project::orderByDesc('id')->Simplepaginate(10);

        return view('projects.index',compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\ProjectRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectRequest $request)
    {
        $project=Project::Create($request->all());

        return redirect()->back()->with('success', 'Project created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\ProjectRequest  $request
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(ProjectRequest $request, Project $project)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }
}

resources/views/projects/index.blade.php
@extends('layouts.app')
@section('content')
@section('title', 'Projects')

<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Create Project
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse {{$errors->has('project_name') ? ' show' : 'hide'}}" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body ">
                    <div class="col-sm-6 center">
                        <form  method="POST" action="{{route('projects.store')}}">
                            @csrf
                            <div class="mb-3">
                                <label for="exampleFormControlInput1" class="form-label">Project</label>
                                <input type="text" name="project_name" class="form-control  {{$errors->has('project_name') ? ' is-invalid' : ''}}" placeholder="Project">                              
                                @if($errors->has('project_name'))
                                    <div id="validationServer05Feedback" class="invalid-feedback">
                                        {{$errors->first('project_name')}}
                                    </div>
                                @endif
                            </div>                                                   
                            <div class="mb-3">
                                <button type="submit" class="btn btn-primary">Create Project</button>
                            </div>   
                        </form>
                    </div>                     
                </div>
            </div>
            </div>
        </div>
        <div class="pt-2">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Project</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($projects as $index=>$project)
                        <tr>
                            <th scope="row">{{$loop->iteration}}</th>
                            <td>{{$project->project_name}}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

          {{$projects->links()}}

        </div>
    </div>
</div>
      
@endsection