routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {

    Route::get('/home', 'HomeController@index')->name('home');
    //projects related routes 
    Route::resource('projects','ProjectController')->only(['index', 'store']);;
    //tasks routes
    Route::resource('tasks','TaskController')->except(['create', 'show']);
    //task status update route
    Route::post('task_status','TaskController@TaskStatus')->name('task_status');
    //setup task order route
    Route::post('task_order','TaskController@TaskOrder')->name('task_order');
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Auth;

class Task extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = ['task_title','project_id','priority','status','order','created_by','updated_by','deleted_by'];

    public function project(){
        return $this->hasone('App\Models\Project','id','project_id');
    }
    public static function boot() {
        parent::boot();
  
        // create a event to happen on updating
        static::updating(function($table)  {
            $table->updated_by = auth()->user()->id;
        });
  
        // create a event to happen on deleting
        static::deleting(function($table)  {
            $table->deleted_by = auth()->user()->id;
        });
  
        // create a event to happen on saving
        static::creating(function($table)  {
            if (Auth::user()) {
                $table->created_by = auth()->user()->id;
            }
        });
      }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use App\Models\Project;
use Illuminate\Http\Request;
use App\Http\Requests\TaskRequest;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::select('id','project_name')->get();
        $tasks=Task::orderByDesc('order')->get();
  
        
        return view('tasks.index',compact('projects','tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\TaskRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TaskRequest $request)
    {   
       
            
            Task::create($request->all());

          

        return redirect()->back()->with('success', 'Task Created successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        $projects = Project::all();
        return [
            'task' => $task,
            'projects' => $projects
        ];
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\TaskRequest  $request
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(TaskRequest $request, Task $task)
    {
        $task->update($request->all());
        return "success";
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {

         $task->delete();
         return redirect()->back()->with('success', 'Task deleted successfully');

    }

    public function TaskStatus(Request $request){

        //update task status if we drag fron one column to another
        $task=Task::find($request->task_id);

        switch ($request->task_status){
            case 'new_task':
                $new_status='0';
            break;
            case 'progress':
                $new_status='1';
            break;
            case 'completed':
                $new_status='2';
            break;
        }

        $request['status']=$new_status;

        $task->update($request->all());

        $tasks= Task::whereStatus($new_status)->get();
      
        return $task;
    }

    public function TaskOrder(Request $request){

        //Task order will setup if we drag top or bottom 

        $ordered_task = array_reverse($request->ordered_task);

        foreach($ordered_task as $index => $order){

            $index = $index+1;

            $task = Task::find($order)->update(['order'=>$index]);
        }
    }
}

app/View/Components/Task.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Task extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.task');
    }
}

resources/views/tasks/index.blade.php
@extends('layouts.app')
@section('content')
@section('title', 'Tasks')

<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" id="task_button">
                Create Task
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse {{$errors->has('task_title') ? ' show' : 'hide'}} task_button" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body ">
                   
                        <form  method="POST" action="{{route('tasks.store')}}" id="task_form">
                            @csrf
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="exampleFormControlInput1" class="form-label">Task Title</label>
                                    <input type="text" name="task_title" class="form-control  {{$errors->has('task_title') ? ' is-invalid' : ''}}" value="{{old('task_title')}}" placeholder="Task Title">                              
                                    @if($errors->has('task_title'))
                                        <div id="validationServer05Feedback" class="invalid-feedback">
                                            {{$errors->first('task_title')}}
                                        </div>
                                    @endif
                                </div>   
                                <div class="col-md-4">
                                    <label for="project" class="form-label">Project</label>
                                    <select class="form-select {{$errors->has('project_id') ? ' is-invalid' : ''}}" name="project_id">
                                        <option selected disabled value="">Choose...</option>

                                        @foreach ($projects as $project)
                                            
                                            <option  value="{{ $project->id}}" {{$project->id == old('project_id') ? ' selected="selected"' : ''}}>{{$project->project_name}}</option>

                                        @endforeach
                                     
                                    </select>
                                    @if($errors->has('project_id'))
                                        <div id="validationServer05Feedback" class="invalid-feedback">
                                            {{$errors->first('project_id')}}
                                        </div>
                                    @endif
                                  </div>                       
                                <div class="col-md-4">
                                    <label for="priority" class="form-label">Priority</label>
                                    <select class="form-select {{$errors->has('priority') ? ' is-invalid' : ''}}"  name="priority">
                                      <option selected disabled value="">Choose...</option>
                                      <option value="0" {{old('priority') =='0' ? 'selected="selected"' : ''}}>Low</option>
                                      <option value="1" {{old('priority') =='1' ? 'selected="selected"' : ''}}>Normal</option>
                                      <option value="2" {{old('priority') =='2' ? 'selected="selected"' : ''}}>High</option>
                                    </select>
                                    @if($errors->has('priority'))
                                        <div id="validationServer05Feedback" class="invalid-feedback">
                                            {{$errors->first('priority')}}
                                        </div>
                                    @endif
                                  </div>                       
                                </div>
                                <div class="row pt-3">

                                    <div class="col-md-3">
                                        <button type="submit" class="btn btn-primary task_button" id="submit">Create Task </button>
                                    </div> 

                                </div>
                        </form>
                              
                </div>
            </div>
            </div>
        </div>
        <div class="row pt-2">
            {{-- New task data component --}}
            @component('components.task',compact('tasks'))    
   
                @slot('parent_id')
                    new_task
                @endslot
        
             @endcomponent

            {{-- In progress task data component --}}
             @component('components.task', compact('tasks'))    
   
                @slot('parent_id')
                    progress
                @endslot
            
             @endcomponent

            {{-- Completed task data component --}}
            @component('components.task', compact('tasks'))    
   
                @slot('parent_id')
                    completed
                @endslot

             @endcomponent 
    
         </div>
    </div>
</div>
    {{-- Task Edit component --}}
   @component('components.task_edit_model', compact('projects'))    
   
   @endcomponent 

@endsection
@push('js')
    <script>

        //drag and drop task jquery ajax
        //drag and drop js is taken from https://codepen.io/tsaiyy/pen/brKdGM?css-preprocessor=scss and customized 

        $(function() {
            $('.parent').on('click', 'section', function() {
                $(this).toggleClass('selected');
            });

            let task_status = '';
            let task_id = '';
            let task_type = '';

            $("div.parent").sortable({
                connectWith: 'div.parent',
                opacity: 0.6,
                revert: true,
                helper: function(e, item) {
                    task_id = item.context.id;
                    task_type = this.id;

                    if (!item.hasClass('selected'))
                        item.addClass('selected');
                    var elements = $('.selected').not('.ui-sortable-placeholder').clone();
                    var helper = $('<div/>');
                    item.siblings('.selected').addClass('hidden');
                    return helper.append(elements);
                },

                start: function(e, ui) {
                    var elements = ui.item.siblings('.selected.hidden').not('.ui-sortable-placeholder');
                    ui.item.data('items', elements);
                },
                receive: function(e, ui) {
                    ui.item.before(ui.item.data('items'));
                    task_status = $(this).attr('id');

                },
                stop: function(e, ui) {
                    ui.item.siblings('.selected').removeClass('hidden');
                    $('.selected').removeClass('selected');
                },
                update: function() {

                    updateTaskOrder(task_type);

                    if (task_status != '' && task_id != '') {

                        $.ajax({
                            type: "POST",
                            url: "{{ url('task_status') }}",
                            data: {
                                task_id,
                                task_status
                            },
                            success: function(response) {

                            }
                        });
                    }
                }

            });

            $("#new_task, #progress, #completed").disableSelection();
            $("#new_task, #progress, #completed").css('minHeight', $("#new_task, #progress").height() + "px");
        });

        function updateTaskOrder(task_type) {

            var ordered_task = [];

            $("#" + task_type + " section").each(function() {
                ordered_task.push($(this).attr('id'));
            });

            $.ajax({
                type: "POST",
                url: "{{ url('task_order') }}",
                data: {
                    ordered_task
                },
                success: function(response) {}
            });


        }

        function editTask(task_id){

            $.ajax({
                type: "GET",
                url: "{{ url('tasks') }}/"+task_id+"/edit",
                success: function(response) {

                $('[name="task_title"]').val(response.task.task_title);
                $('#priority').val(response.task.priority).change();
                $('#project_id').val(response.task.project_id).change();
                $('#task_id').val(response.task.id);
                $('[name="task_title"]').attr("required", "true");
                }
            });
        
        }

        function updateTask(){
            var task_id = $("#task_id").val();
            $.ajax({
                type: "PATCH",
                url: "{{ url('tasks') }}/"+task_id,
                data:$('#task_edit_form').serialize(),
                success: function(response) {
                    window.location.reload();
                },
                error: function (xhr) {

                    if(xhr.status === 422){
                        $('#task_title_error').show();
                        $('#task_title_error').html(xhr.responseJSON.errors["task_title"][0]);
                    }
            }
            });

        }

    </script>
@endpush